name: Auto Retrain Pipeline

on:
  push:
    paths:
      - 'data/new_data/*.csv'

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          pip install xgboost shap imbalanced-learn streamlit scikit-learn pandas numpy matplotlib seaborn pytest

      - name: run training pipeline
        run: |
          python src/train.py

      - name: run tests
        run: |
          pytest tests/test_preprocess.py -v

      - name: save updated model
        if: success()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add model/ data/creditcard.csv data/append_log.csv
          git commit -m "auto retrained model - $(date +'%Y-%m-%d')"
          git push